### ISSUE TITLE
Dedupe process never finishes on large files (100k+ rows)

### ISSUE THREAD

**Issue by cfatls** [Lyonk71/pandas-dedupe#35]
I've had great success using the library, with files from 50k to 100k rows, 8 columns. 
Incredible ease of use.
However, when trying to perform the process on a larger scale (205000 rows, 19 columns), the "Clustering..." part of the run never seems to end and is just stuck there. I don't Know what might be causing it.  I've used 4 fields as criteria for training the model.
Using Manjaro Linux 20.2 / Python 3.8.6

Disclaimer: Python Noob.

**Comment by cfatls** [comment]
Tried splitting the file into several smaller ones (70k). Could only go through 1st file just fine.
Going through the second file, got this message:

Reading from dedupe_dataframe_learned_settings
Clustering...
WARNING:dedupe.clustering:A component contained 35847 elements. Components larger than 30000 are re-filtered. The threshold for this filtering is 6.0306406612178405e-09

Any pointers would be appreciated.

**Comment by ieriii** [comment]
Hi! Thanks for your message :)

This is not really an issue with pandas-dedupe itself but rather a _warning_ that stem from a design choice of dedupe (i.e. the library pandas-dedupe is built on top). You can read more about it here: https://readthedocs.org/projects/dedupe-staging/downloads/pdf/stable/ (see page 9, match() ).

In general, pandas-dedupe works well with small and medium size dataset.
For larger dataset, you might want to think about something like a dedupe sql implementation.

Since this is a warning and not an error or a bug, I'm inclined to close this issue unless you have further comments.
Thanks :)
